### ISSUE TITLE
Repo access

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-support-network#21]
@smashwilson  Can you give the How-To team Admin access to the https://github.com/rackerlabs/docs-support-network repository, so they can review the collaborator and webhook info if needed?

Also, the updates in this repo don't seem to be getting deployed to the [support.rackspace.com](https://support.rackspace.com/) landing page.

It looks like the  [Travis build job](https://github.com/rackerlabs/docs-support-network/blob/master/.travis.yml) is not deploying the content. Maybe the repo needs to have a Strider build configured? (Last Travis build that shows content submission is [#35](https://travis-ci.org/rackerlabs/docs-support-network/builds/122856295))

I know that Keith moved the assets and layouts to the nexus-control repository as described in the [Readme.md](https://github.com/rackerlabs/docs-support-network/blob/master/README.md).

*Nexus-control has the following config files:*
 - [content.d](https://github.com/rackerlabs/nexus-- control/blob/master/config/content.d/support.rackspace.com.json)

- [routes.d](https://github.com/rackerlabs/nexus-
control/blob/master/config/routes.d/support.rackspace.com.json) files configured.  

- Configured template =  [deferred.html](https://github.com/rackerlabs/nexus-control/commit/d9a518a5342d8c05d6ed2a26efa4b00cbfce1c5e)  

If a Strider build is needed,  Nate submitted a [PR](https://github.com/rackerlabs/nexus-control/pull/601) to add the repo to the content.repositories.json file.  Still need to add the RackerNexus user to this repo.

**Comment by smashwilson** [comment]
> @smashwilson Can you give the How-To team Admin access to the https://github.com/rackerlabs/docs-support-network repository, so they can review the collaborator and webhook info if needed?

There already is a [rackspace-howto-admin team](https://github.com/orgs/rackerlabs/teams/rackspace-howto-admin) with admin access here:

![screen shot 2016-10-05 at 8 32 13 am](https://cloud.githubusercontent.com/assets/17565/19113148/539c62c8-8ad6-11e6-8e61-69421da86e68.jpeg)

I went ahead and added you, so you should have admin access now. It looks like @lauracly and @ReneeRendon can add new members, too.

> Also, the updates in this repo don't seem to be getting deployed to the support.rackspace.com landing page.
>
> It looks like the Travis build job is not deploying the content. Maybe the repo needs to have a Strider build configured? (Last Travis build that shows content submission is #35)

Ohhh - yes, I refactored content submission into its own component. I must have neglected bringing this repository up to date when I did that.

The easiest way to get this working would be to set it up in Strider. (You'd be able to see its build status in the same place as the others, too). I'll shuffle that through presently.

**Comment by meker12** [comment]
So the header is still there, but that's another issue.
