### ISSUE TITLE
Link to Getting Started with Rackspace Cloud Cloud is broken

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-support-network#6]
![rackspace_support-broken-rpc-link](https://cloud.githubusercontent.com/assets/6391769/12927227/b2e016b4-cf2c-11e5-8761-27ec2b372ad3.png)

**Comment by meker12** [comment]
@klevenstein Do you know the correct target URL for the link above?

**Comment by klevenstein** [comment]
I believe it ought to be this: https://support.rackspace.com/how-to/rpc-openstack/

**Comment by meker12** [comment]
Fixed by PR #7 .
